version: '2'
services:
  app:
    build: docker/app
    volumes:
      - .:/var/www/quiz
    working_dir: /var/www/quiz
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    image: nginx:1.15
    volumes:
      - ./etc/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    working_dir: /var/www/quiz
    ports:
      - 8080:80
  database:
    image: mysql:5.7
    volumes:
      - quizdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=quiz_main"
      - "MYSQL_USER=quiz_sql"
      - "MYSQL_PASSWORD=quiz_password"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  quizdata:
